source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'STMReactiveAlert_Example', :exclusive => true do
  pod "STMReactiveAlert", :path => "../"
end

target 'STMReactiveAlert_Tests', :exclusive => true do
  pod "STMReactiveAlert", :path => "../"

  
end
